-- NexusSphere Bulk Song Sync Script
-- This registers all currently existing songs in the project into the 'songs' table.
-- Using INSERT OR IGNORE to prevent duplicates.

INSERT OR IGNORE INTO songs (slug, title, asset_path) VALUES 
('after-the-last-hit', 'After the Last Hit', 'assets/audio/generated_midi/After_the_Last_Hit.mid'),
('before-the-game-starts', 'Before The Game Starts', 'assets/audio/generated_midi/Before_The_Game_Starts.mid'),
('keys-by-the-hearth', 'Keys by the Hearth', 'assets/audio/generated_midi/Keys_by_the_Hearth.mid'),
('kiminoegao1', 'KiminoEgao1', 'assets/audio/generated_midi/KiminoEgao1.mid'),
('kiminoegao2', 'KiminoEgao2', 'assets/audio/generated_midi/KiminoEgao2.mid'),
('paper-lanterns-rising', 'Paper Lanterns Rising', 'assets/audio/generated_midi/Paper_Lanterns_Rising.mid'),
('platinum-gates', 'Platinum Gates', 'assets/audio/generated_midi/Platinum_Gates.mid'),
('vector-override', 'Vector Override', 'assets/audio/generated_midi/Vector_Override.mid'),
('waltz-for-lily', 'Waltz for Lily', 'assets/audio/generated_midi/Waltz for Lily - King & Prince (128k).mid'),
('westbound-at-sunset', 'Westbound at Sunset', 'assets/audio/generated_midi/Westbound_at_Sunset.mid'),
('what-we-got', 'What We Got', 'assets/audio/generated_midi/What We Got ～奇跡は기미토～ - Disney - Topic (128k).mid'),
('where-iron-meets-the-ember', 'Where Iron Meets the Ember', 'assets/audio/generated_midi/Where_Iron_Meets_the_Ember.mid'),
('your-smiling-face', 'Your Smiling Face', 'assets/audio/generated_midi/Your Smiling Face.mid'),
('your-smiling-face2', 'Your Smiling Face2', 'assets/audio/generated_midi/Your Smiling Face2.mid'),
('soba-ni-iru-kara', 'そばにいるから', 'assets/audio/generated_midi/そば에いるから.mid'),
('ii-jan', 'イイじゃん', 'assets/audio/generated_midi/イイじゃん - M!LK (128k).mid'),
('charisma-max', 'カリスマックス', 'assets/audio/generated_midi/カリスマックス - Snow Man (128k).mid'),
('brother-beat', 'ブラザービート', 'assets/audio/generated_midi/ブラザービート - Snow Man (128k).mid'),
('omoi-wa-meguru', '想이는廻る', 'assets/audio/generated_midi/想이는廻る.mid'),
('your-meaning', '너의 의미', 'assets/audio/generated_midi/너의 의미.mid'),
('your-meaning2', '너의 의미2', 'assets/audio/generated_midi/너의 의미2.mid'),
('azure-ballroom', '옥빛 바다 무도회', 'assets/audio/generated_midi/옥빛_바다_무도회.mid'),
('reach-higher', '정상을 향해 더 높이', 'assets/audio/generated_midi/정상을_향해_더_높이.mid'),
('ballade-pour-adeline', 'Ballade pour Adeline', 'assets/audio/midi/ballade-pour-adeline.mid'),
('begining', 'Begining', 'assets/audio/midi/begining.mid'),
('bloody-tears', 'Bloody Tears', 'assets/audio/midi/Bloody_Tears.mid'),
('bublbobl', 'Bubble Bobble', 'assets/audio/midi/BublBobl_RK.mid'),
('corazonazul', 'Corazonazul (FF6 Boss)', 'assets/audio/midi/corazonazul_ff6boss.mid'),
('vampire-killer', 'Vampire Killer', 'assets/audio/midi/CV1-_Vampire_Killer.mid'),
('doom-e1m1', 'DOOM - At Dooms Gate', 'assets/audio/midi/DOOM - Robert C. Prince - E1M1 - At Doom''s Gate.mid'),
('dragon-warrior-3', 'Dragon Warrior 3 Overworld', 'assets/audio/midi/ENIX_-_Dragon_Warrior_3_(_Overworld_BGM_).mid'),
('ff6-fierce-battle', 'FF6 The Fierce Battle', 'assets/audio/midi/FF6_The_Fierce_Battle_Xg.mid'),
('melodies-of-life', 'Melodies of Life', 'assets/audio/midi/melodies_of_life.mid'),
('one-winged-angel', 'One-Winged Angel', 'assets/audio/midi/One-Winged_Angel.mid'),
('pirates-of-caribbean', 'Pirates of the Caribbean', 'assets/audio/midi/Pirates of the Caribbean - He''s a Pirate (1).mid'),
('swan-lake', '백조의 호수', 'assets/audio/midi/백조의호수.mid'),
('air-wolf', '에어울프', 'assets/audio/midi/에어울프.mid'),
('turkish-march', '터키행진곡', 'assets/audio/midi/터키행진곡.mid');
