import type { ParsedMidi, GameNote } from '../../core/audio/MidiParser';
import { MelodyAnalyzer } from '../../core/audio/MelodyAnalyzer';
import { RhythmQuantizer, type QuantizedNote } from './logic/RhythmQuantizer';
import { PatternAnalyzer } from './logic/PatternAnalyzer';
import { LaneAllocator } from './logic/LaneAllocator';
import { DifficultyManager } from './logic/DifficultyManager';

export interface VisualNote extends GameNote {
    lane: number;
    isProcessed: boolean;
    quantizedStartTick?: number;
    quantizedEndTick?: number;
    isOnBeat?: boolean;
    isStrongBeat?: boolean;
    // Long Note Props
    durationMs: number;
    isHold: boolean;
    endTick: number; // For logic
    isHolding: boolean; // Runtime state
    accumulatedHoldTime: number; // For tick combo
    type: 'TAP' | 'HOLD';
}

export class NoteFactory {
    public static createNotes(
        midi: ParsedMidi,
        laneCount: number = 4,
        forcedChannels: number[] | null = null,
        difficulty: string = 'NORMAL',
        measureConfig: [number, number][] | null = null
    ): VisualNote[] {
        const ppq = midi.ppq;
        const isAiGenerated = midi.tracks.some(t => t.name?.toLowerCase().includes('main gameplay'));

        const diffManager = new DifficultyManager(difficulty, { 
            isAiGenerated, 
            bpm: midi.bpm, 
            ppq: midi.ppq 
        });
        const effectiveDifficulty = diffManager.getEffectiveDifficulty();

        // 1. Convert measureConfig array to Map if available
        const measureMap = new Map<number, number>();
        if (measureConfig && Array.isArray(measureConfig)) {
            measureConfig.forEach(entry => {
                if (Array.isArray(entry) && entry.length >= 2) {
                    measureMap.set(Number(entry[0]), Number(entry[1]));
                }
            });
        }

        // Helper: Get Primary channel for a given measure
        // Determine Default Auto Primary for entire song if measureMap is empty or unavailable
        let autoGeneratedConfig: Map<number, number> | null = null;
        if (measureMap.size === 0) {
            console.log("[NoteFactory] No measure map found. Generating intelligence Magic configuration...");
            
            const ranked = MelodyAnalyzer.findMelodyTracks(midi);
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi, ranked);
            
            // [Phase 8] Centralized Architectural Refinement
            // Delegate the structural "Gap Filling" strategy to the DifficultyManager using TRACK indices.
            if (isAiGenerated) {
                diffManager.refineAiChartStrategy(autoGeneratedConfig, midi, ranked);
            }
        }


        const notes: GameNote[] = [];

        const collectNotes = (map: Map<number, number>, autoMap: Map<number, number> | null) => {
            midi.tracks.forEach((track, trackIndex) => {
                track.notes.forEach(note => {
                    if (note.velocity < 13) return; // Ghost note gate

                    const mIdx = Math.floor(note.ticks / (ppq * 4));
                    let targetTrackIdx = null;

                    if (map.size > 0) {
                        targetTrackIdx = map.get(mIdx) ?? null;
                    } else if (autoMap) {
                        targetTrackIdx = autoMap.get(mIdx) ?? null;
                    }

                    // [Phase 8] Perfect Isolation via Track Index comparison
                    if (targetTrackIdx !== null && trackIndex === targetTrackIdx) {
                        (note as any).isPrimary = true;
                        notes.push(note);
                    }
                });
            });
            return notes;
        };

        let initialNotes = collectNotes(measureMap, autoGeneratedConfig);

        // [FALLBACK] If no notes were found with current config (usually due to channel mismatch),
        // Force a re-analysis and try again.
        if (initialNotes.length === 0 && !forcedChannels) {
            console.warn(`[NoteFactory] 0 notes collected with provided config. Triggering Emergency Magic Analysis...`);
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
            initialNotes = collectNotes(new Map(), autoGeneratedConfig);
        }

        const finalNotes = initialNotes;
        console.log(`[NoteFactory] Collected ${finalNotes.length} notes based on configuration.`);

        // DEBUG: Ensure there is at least one primary channel detected/processed
        if (measureMap.size > 0) {
            console.log(`[NoteFactory] Processed with defined Measure Map entries: ${measureMap.size}`);
        } else if (autoGeneratedConfig) {
            console.log(`[NoteFactory] Intelligence Magic configuration applied (Segments: ${autoGeneratedConfig.size})`);
        } else {
            console.warn(`[NoteFactory] No configuration available. Generating empty chart.`);
        }

        let notesToProcess = finalNotes
            .filter(n => n.duration > 0.01) // Filter out < 10ms flicker notes
            .sort((a, b) => a.ticks - b.ticks);

        if (notesToProcess.length > 20000) {
            console.warn(`[NoteFactory] MIDI too dense (${notesToProcess.length} notes). Capping to 20,000 for stability.`);
            notesToProcess = notesToProcess.slice(0, 20000);
        }

        if (notesToProcess.length === 0) {
            console.warn("[NoteFactory] Failed to find any notes for charting. Returning empty list (Fallback Triggered).");
            return [];
        }

        // 1. Quantize first
        const quantized = RhythmQuantizer.quantize(notesToProcess, midi.ppq);

        // 2. Collapse Chords BASED ON QUANTIZED TICKS (The Fix for jittery MIDI)
        const collapsed: QuantizedNote[] = [];
        const seenCounts = new Map<string, number>();
        quantized.forEach(n => {
            if (!diffManager.shouldAcceptNote(n)) return;

            const key = diffManager.isGlobalChordSuppressionActive()
                ? `GLOBAL_${n.quantizedStartTick}`
                : `${n.channel}_${n.quantizedStartTick}`;

            const count = seenCounts.get(key) || 0;
            if (count < diffManager.getNoteChordLimit()) {
                collapsed.push(n);
                seenCounts.set(key, count + 1);
                diffManager.recordAcceptedNote(n);
            }
        });

        // 3. Apply Time Correction (Sync Fix)
        RhythmQuantizer.applyTimeCorrection(collapsed, midi);

        const preparedNotes = collapsed.map(n => {
            let durationMs = n.duration * 1000;
            let isHold = false;
            
            if (isAiGenerated) {
                // Use adaptive threshold from DifficultyManager. 
                // Default is 150ms, but increased for NORMAL/EASY to filter noise.
                isHold = durationMs >= diffManager.getAiHoldThresholdMs();
            } else {
                // Legacy logic for manual charts
                isHold = durationMs >= diffManager.getHoldThresholdMs();
            }

            // AI-NORMAL now trusts the melodic sustain detected by pYIN.
            // (Removed off-beat hold suppression)

            return {
                ...n,
                durationMs: durationMs,
                isHold: isHold,
                endTick: n.ticks + (isHold ? n.durationTicks : Math.round((80 / 1000) * (midi.ppq * midi.bpm / 60))), 
                isHolding: false,
                accumulatedHoldTime: 0,
                type: isHold ? 'HOLD' : 'TAP',
                lane: -1,
                isProcessed: false
            } as VisualNote;
        });

        const patterns = PatternAnalyzer.analyze(preparedNotes as any[]);
        let finalResult = LaneAllocator.assignLanes(patterns, laneCount, effectiveDifficulty);
        
        // 4. [NEW] Trim Hand Conflicts
        // Ensure no long note overlaps with a subsequent note on the same hand.
        finalResult = this.trimHandConflicts(finalResult, laneCount);

        console.log(`[NoteFactory] Charted ${finalResult.length} notes (Holds: ${finalResult.filter(n => n.isHold).length}).`);
        if (finalResult.length > 0) {
            console.log(`[NoteFactory] First 5 notes sample:`, finalResult.slice(0, 5).map(n => ({
                tick: n.ticks, time: n.time, lane: n.lane, duration: n.duration, isHold: n.isHold
            })));
        }
        if (finalResult.length > 20000) {
            return finalResult.slice(0, 20000);
        }
        return finalResult;
    }

    /**
     * Post-processing pass: Trims long note durations if they conflict with 
     * a same-hand, different-lane note starting later.
     */
    private static trimHandConflicts(notes: VisualNote[], laneCount: number): VisualNote[] {
        // Ensure notes are sorted by time for linear scan
        const sorted = [...notes].sort((a, b) => a.time - b.time);
        
        const activeHoldInHand: { 'left': VisualNote | null, 'right': VisualNote | null } = {
            'left': null,
            'right': null
        };

        const getHand = (lane: number): 'left' | 'right' => {
            if (laneCount === 4) return lane < 2 ? 'left' : 'right';
            return lane < 3 ? 'left' : 'right';
        };

        const bufferMs = 30; // 30ms gap to ensure release before next hit

        for (const note of sorted) {
            const hand = getHand(note.lane);
            const activeHold = activeHoldInHand[hand];

            // 1. If there's an active hold in the SAME HAND area...
            if (activeHold && activeHold !== note) {
                const holdEndTime = activeHold.time + (activeHold.durationMs / 1000);
                
                // 2. And it overlaps with the current note's start...
                // (Only if it's in a DIFFERENT lane, as same-lane overlap is already handled by hardware/allocator)
                if (activeHold.lane !== note.lane && holdEndTime > note.time - (bufferMs / 1000)) {
                    // 3. Trim it!
                    const newDurationMs = Math.max(0, (note.time - activeHold.time) * 1000 - bufferMs);
                    activeHold.durationMs = newDurationMs;
                    activeHold.duration = newDurationMs / 1000;
                    
                    // If it was trimmed to basically zero, it's effectively a tap
                    if (newDurationMs < 100) {
                        activeHold.isHold = false;
                        activeHold.type = 'TAP';
                    }
                    
                    // Clear it as it's now "ended" before this note
                    activeHoldInHand[hand] = null;
                }
            }

            // If current note is a hold, track it as the active one for this hand
            if (note.isHold) {
                activeHoldInHand[hand] = note;
            }

            // Cleanup: If a hold ended naturally before this note, clear the tracker
            ['left', 'right'].forEach((h: any) => {
                const hold = activeHoldInHand[h as 'left' | 'right'];
                if (hold && hold.time + (hold.durationMs / 1000) <= note.time) {
                    activeHoldInHand[h as 'left' | 'right'] = null;
                }
            });
        }

        return sorted;
    }
}
