import type { ParsedMidi, GameNote } from '../../core/audio/MidiParser';
import { MelodyAnalyzer } from '../../core/audio/MelodyAnalyzer';
import { RhythmQuantizer, type QuantizedNote } from './logic/RhythmQuantizer';
import { PatternAnalyzer } from './logic/PatternAnalyzer';
import { LaneAllocator } from './logic/LaneAllocator';
import { DifficultyManager } from './logic/DifficultyManager';
import { LegacyNoteFactory } from './logic/legacy/LegacyNoteFactory';

export interface VisualNote extends GameNote {
    lane: number;
    isProcessed: boolean;
    quantizedStartTick?: number;
    quantizedEndTick?: number;
    isOnBeat?: boolean;
    isStrongBeat?: boolean;
    // Long Note Props
    durationMs: number;
    isHold: boolean;
    endTick: number; // For logic
    isHolding: boolean; // Runtime state
    accumulatedHoldTime: number; // For tick combo
    type: 'TAP' | 'HOLD';
}

export class NoteFactory {
    public static createNotes(
        midi: ParsedMidi,
        laneCount: number = 4,
        forcedChannels: number[] | null = null,
        difficulty: string = 'NORMAL',
        measureConfig: [number, number][] | null = null
    ): VisualNote[] {
        const ppq = midi.ppq;
        const isAiGenerated = midi.tracks.some(t => t.name?.toLowerCase().includes('main gameplay'));

        const diffManager = new DifficultyManager(difficulty, { 
            isAiGenerated, 
            bpm: midi.bpm, 
            ppq: midi.ppq 
        });
        const effectiveDifficulty = diffManager.getEffectiveDifficulty();

        // 1. Convert measureConfig array to Map if available
        const measureMap = new Map<number, number>();
        if (measureConfig && Array.isArray(measureConfig)) {
            measureConfig.forEach(entry => {
                if (Array.isArray(entry) && entry.length >= 2) {
                    measureMap.set(Number(entry[0]), Number(entry[1]));
                }
            });
        }

        // Helper: Get Primary channel for a given measure
        let autoGeneratedConfig: Map<number, number> | null = null;
        if (measureMap.size === 0) {
            console.log("[NoteFactory] No measure map found. Generating intelligence Magic configuration...");
            
            const ranked = MelodyAnalyzer.findMelodyTracks(midi);
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi, ranked);
            
            if (isAiGenerated) {
                diffManager.refineAiChartStrategy(autoGeneratedConfig, midi, ranked);
            }
        }

        // [Phase 10] BIFURCATION: Route to Ironclad Legacy Engine for Standard MIDI
        if (!isAiGenerated) {
            console.log(`[NoteFactory] SANCTUARY: Standard MIDI Legacy Engine (v1d75924) Activated.`);
            return LegacyNoteFactory.createLegacyNotes(
                midi,
                laneCount,
                forcedChannels,
                difficulty,
                measureConfig
            ) as any as VisualNote[];
        }

        // --- CONTINUE WITH AI-ADVANCED PATH (8584017) ---
        console.log(`[NoteFactory] AI_ADVANCED Logic Activated for Analysis Chart.`);

        const collectNotes = (map: Map<number, number>, autoMap: Map<number, number> | null) => {
            const notesToReturn: GameNote[] = [];
            midi.tracks.forEach((track, trackIndex) => {
                track.notes.forEach(note => {
                    if (note.velocity < 13) return; // Ghost note gate

                    const p = ppq || 480;
                    const mIdx = Math.floor(note.ticks / (p * 4));
                    let targetTrackIdx = null;

                    if (map.size > 0) {
                        targetTrackIdx = map.get(mIdx) ?? null;
                    } else if (autoMap) {
                        targetTrackIdx = autoMap.get(mIdx) ?? null;
                    }

                    const isPrimary = (targetTrackIdx !== null && trackIndex === targetTrackIdx);
                    const isDrum = track.isDrum || (track.name?.toLowerCase().includes('drums'));
                    
                    let shouldAccept = false;
                    
                    if (isPrimary) {
                        shouldAccept = true;
                    } else if (isDrum && diffManager.shouldIncludeDrums()) {
                        shouldAccept = true;
                    } else if (!isDrum && diffManager.shouldIncludeExtraTracks()) {
                        shouldAccept = true;
                    }

                    if (shouldAccept) {
                        const n = { ...note };
                        if (isPrimary) (n as any).isPrimary = true;
                        notesToReturn.push(n);
                    }
                });
            });
            return notesToReturn;
        };

        let initialNotes = collectNotes(measureMap, autoGeneratedConfig);

        // Fallback 1: Strategic Gap Filling
        if (initialNotes.length === 0 && !forcedChannels) {
            console.warn(`[NoteFactory] 0 notes collected with provided config. Triggering Emergency Magic Analysis...`);
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
            initialNotes = collectNotes(new Map(), autoGeneratedConfig);
        }

        // Fallback 2: Final Safety Net - Force highest ranked track if still zero
        if (initialNotes.length === 0 && !forcedChannels) {
            const ranked = MelodyAnalyzer.findMelodyTracks(midi);
            if (ranked.length > 0) {
                console.warn(`[NoteFactory] Still zero notes. FORCING track ${ranked[0]} for entire song.`);
                const emergencyMap = new Map<number, number>();
                const totalMeasures = Math.ceil((midi as any).durationTicks / (ppq * 4)) || 1000;
                for (let i = 0; i < totalMeasures; i++) emergencyMap.set(i, ranked[0]);
                initialNotes = collectNotes(new Map(), emergencyMap);
            }
        }

        const finalNotes = initialNotes;
        let notesToProcess = finalNotes
            .filter(n => n.duration > 0.01)
            .sort((a, b) => a.ticks - b.ticks);

        if (notesToProcess.length > 20000) {
            notesToProcess = notesToProcess.slice(0, 20000);
        }

        if (notesToProcess.length === 0) return [];

        // 1. Quantize
        const quantized = RhythmQuantizer.quantize(notesToProcess, midi.ppq);

        // Sort by primary status to ensure vocal/melody priority during monophonic collapse
        quantized.sort((a, b) => {
            if (a.quantizedStartTick !== b.quantizedStartTick) return a.quantizedStartTick - b.quantizedStartTick;
            return ((b as any).isPrimary ? 1 : 0) - ((a as any).isPrimary ? 1 : 0);
        });

        // 2. Collapse Chords
        const collapsed: QuantizedNote[] = [];
        const seenCounts = new Map<string, number>();
        quantized.forEach(n => {
            if (!diffManager.shouldAcceptNote(n)) return;

            const key = diffManager.isGlobalChordSuppressionActive()
                ? `GLOBAL_${n.quantizedStartTick}`
                : `${n.channel}_${n.quantizedStartTick}`;

            const count = seenCounts.get(key) || 0;
            if (count < diffManager.getNoteChordLimit()) {
                collapsed.push(n);
                seenCounts.set(key, count + 1);
                diffManager.recordAcceptedNote(n);
            }
        });

        // 3. Time Correction
        RhythmQuantizer.applyTimeCorrection(collapsed, midi);

        const preparedNotes = collapsed.map(n => {
            let durationMs = n.duration * 1000;
            let isHold = durationMs >= diffManager.getAiHoldThresholdMs();
            
            return {
                ...n,
                durationMs: durationMs,
                isHold: isHold,
                endTick: n.ticks + (isHold ? n.durationTicks : Math.round((80 / 1000) * (midi.ppq * midi.bpm / 60))), 
                isHolding: false,
                accumulatedHoldTime: 0,
                type: isHold ? 'HOLD' : 'TAP',
                lane: -1,
                isProcessed: false
            } as VisualNote;
        });

        const patterns = PatternAnalyzer.analyze(preparedNotes as any[]);
        let finalResult = LaneAllocator.assignLanes(patterns, laneCount, effectiveDifficulty);
        finalResult = this.trimHandConflicts(finalResult, laneCount);

        return finalResult;
    }

    private static trimHandConflicts(notes: VisualNote[], laneCount: number): VisualNote[] {
        const sorted = [...notes].sort((a, b) => a.time - b.time);
        const activeHoldInHand: { 'left': VisualNote | null, 'right': VisualNote | null } = {
            'left': null, 'right': null
        };
        const getHand = (lane: number): 'left' | 'right' => {
            if (laneCount === 4) return lane < 2 ? 'left' : 'right';
            return lane < 3 ? 'left' : 'right';
        };
        const bufferMs = 30;

        for (const note of sorted) {
            const hand = getHand(note.lane);
            const activeHold = activeHoldInHand[hand];
            if (activeHold && activeHold !== note) {
                const holdEndTime = activeHold.time + (activeHold.durationMs / 1000);
                if (activeHold.lane !== note.lane && holdEndTime > note.time - (bufferMs / 1000)) {
                    const newDurationMs = Math.max(0, (note.time - activeHold.time) * 1000 - bufferMs);
                    activeHold.durationMs = newDurationMs;
                    activeHold.duration = newDurationMs / 1000;
                    if (newDurationMs < 100) {
                        activeHold.isHold = false;
                        activeHold.type = 'TAP';
                    }
                    activeHoldInHand[hand] = null;
                }
            }
            if (note.isHold) activeHoldInHand[hand] = note;
            ['left', 'right'].forEach((h: any) => {
                const hold = activeHoldInHand[h as 'left' | 'right'];
                if (hold && hold.time + (hold.durationMs / 1000) <= note.time) {
                    activeHoldInHand[h as 'left' | 'right'] = null;
                }
            });
        }
        return sorted;
    }
}
