import type { ParsedMidi, GameNote } from '../../core/audio/MidiParser';
import { MelodyAnalyzer } from '../../core/audio/MelodyAnalyzer';
import { RhythmQuantizer, type QuantizedNote } from './logic/RhythmQuantizer';
import { PatternAnalyzer } from './logic/PatternAnalyzer';
import { LaneAllocator } from './logic/LaneAllocator';

export interface VisualNote extends GameNote {
    lane: number;
    isProcessed: boolean;
    quantizedStartTick?: number;
    quantizedEndTick?: number;
    isOnBeat?: boolean;
    isStrongBeat?: boolean;
    // Long Note Props
    durationMs: number;
    isHold: boolean;
    endTick: number; // For logic
    isHolding: boolean; // Runtime state
    accumulatedHoldTime: number; // For tick combo
    type: 'TAP' | 'HOLD';
}

export class NoteFactory {
    public static createNotes(
        midi: ParsedMidi,
        laneCount: number = 4,
        forcedChannels: number[] | null = null,
        difficulty: string = 'NORMAL',
        measureConfig: [number, number][] | null = null
    ): VisualNote[] {
        const ppq = midi.ppq;
        const isAiGenerated = midi.tracks.some(t => t.name?.toLowerCase().includes('main gameplay'));

        // Stage 1 Difficulty Shift for AI-generated songs
        let effectiveDifficulty = difficulty;
        if (isAiGenerated) {
            console.log(`[NoteFactory] AI-Generated MIDI detected. Applying difficulty shift...`);
            if (difficulty === 'EXTREME') effectiveDifficulty = 'HARD';
            else if (difficulty === 'HARD') effectiveDifficulty = 'NORMAL';
            else if (difficulty === 'NORMAL') effectiveDifficulty = 'NORMAL'; // NORMAL now matches HARD's timing
            else effectiveDifficulty = 'EASY'; // Default for AI Easy
        }

        // 1. Convert measureConfig array to Map if available
        const measureMap = new Map<number, number>();
        if (measureConfig && Array.isArray(measureConfig)) {
            measureConfig.forEach(entry => {
                if (Array.isArray(entry) && entry.length >= 2) {
                    measureMap.set(Number(entry[0]), Number(entry[1]));
                }
            });
        }

        // Helper: Get Primary channel for a given measure
        // Determine Default Auto Primary for entire song if measureMap is empty or unavailable
        let autoGeneratedConfig: Map<number, number> | null = null;
        if (measureMap.size === 0) {
            console.log("[NoteFactory] No measure map found. Generating intelligence Magic configuration...");
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
        }


        // 2. Iterate through ALL notes and ONLY keep if they match the measure's primary channel
        // or if they are forced overrides (Test mode soloing etc).
        const collectNotes = (map: Map<number, number>, autoMap: Map<number, number> | null) => {
            const notes: GameNote[] = [];
            midi.tracks.forEach(track => {
                track.notes.forEach(note => {
                    if (note.velocity < 13) return;
                    const measureIdx = Math.floor(note.ticks / (ppq * 4));
                    if (forcedChannels && forcedChannels.length > 0) {
                        if (forcedChannels.includes(note.channel)) notes.push(note);
                        return;
                    }
                    
                    // Specific logic for getMeasurePrimaryChannel inside closure to use provided maps
                    let targetChannel = null;
                    if (map.has(measureIdx)) targetChannel = map.get(measureIdx)!;
                    else if (autoMap && autoMap.has(measureIdx)) targetChannel = autoMap.get(measureIdx)!;
                    else {
                        for (let i = measureIdx; i >= 0; i--) {
                            if (map.has(i)) { targetChannel = map.get(i)!; break; }
                            if (autoMap && autoMap.has(i)) { targetChannel = autoMap.get(i)!; break; }
                        }
                    }

                    if (targetChannel !== null && note.channel === targetChannel) {
                        (note as any).isPrimary = true;
                        notes.push(note);
                    }
                });
            });
            return notes;
        };

        let initialNotes = collectNotes(measureMap, autoGeneratedConfig);

        // [FALLBACK] If no notes were found with current config (usually due to channel mismatch),
        // Force a re-analysis and try again.
        if (initialNotes.length === 0 && !forcedChannels) {
            console.warn(`[NoteFactory] 0 notes collected with provided config. Triggering Emergency Magic Analysis...`);
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
            initialNotes = collectNotes(new Map(), autoGeneratedConfig);
        }

        const finalNotes = initialNotes;
        console.log(`[NoteFactory] Collected ${finalNotes.length} notes based on configuration.`);

        // DEBUG: Ensure there is at least one primary channel detected/processed
        if (measureMap.size > 0) {
            console.log(`[NoteFactory] Processed with defined Measure Map entries: ${measureMap.size}`);
        } else if (autoGeneratedConfig) {
            console.log(`[NoteFactory] Intelligence Magic configuration applied (Segments: ${autoGeneratedConfig.size})`);
        } else {
            console.warn(`[NoteFactory] No configuration available. Generating empty chart.`);
        }

        let notesToProcess = finalNotes
            .filter(n => n.duration > 0.01) // Filter out < 10ms flicker notes
            .sort((a, b) => a.ticks - b.ticks);

        if (notesToProcess.length > 20000) {
            console.warn(`[NoteFactory] MIDI too dense (${notesToProcess.length} notes). Capping to 20,000 for stability.`);
            notesToProcess = notesToProcess.slice(0, 20000);
        }

        if (notesToProcess.length === 0) {
            console.warn("[NoteFactory] Failed to find any notes for charting. Returning empty list (Fallback Triggered).");
            return [];
        }

        // 1. Quantize first
        const quantized = RhythmQuantizer.quantize(notesToProcess, midi.ppq);

        // 2. Collapse Chords BASED ON QUANTIZED TICKS (The Fix for jittery MIDI)
        const collapsed: QuantizedNote[] = [];
        const seenCounts = new Map<string, number>();
        const maxLimit = (effectiveDifficulty === 'HARD') ? 2 : 1;

        // EASY Mode Throttle: Scale minimum gap based on BPM
        let easyMinGap = midi.ppq / 2; // Default 1/8 note
        if (midi.bpm >= 180) {
            easyMinGap = midi.ppq * 2; // 1/2 note for very fast songs
        } else if (midi.bpm >= 110) {
            easyMinGap = midi.ppq; // 1/4 note for fast/medium songs
        }

        let lastAcceptedTick = -99999;
        const beatDurationMs = 60000 / midi.bpm;
        const holdThresholdMs = beatDurationMs * 0.75;

        quantized.forEach(n => {
            if (effectiveDifficulty === 'EASY') {
                // Standard EASY Throttle: Scale minimum gap based on BPM
                // Drop notes that are too fast
                // IMPORTANT: Do NOT drop notes that are strictly simultaneous (gap = 0).
                const tickDiff = n.quantizedStartTick - lastAcceptedTick;
                if (tickDiff > 0 && tickDiff < easyMinGap) {
                    return;
                }
            }

            // [NEW] AI-NORMAL: Melody Only + Basic Rhythm Guard
            if (isAiGenerated && difficulty === 'NORMAL') {
                // Skip Drums (MIDI < 60 are typically Kick/Snare in our transcription)
                if (n.midi && n.midi < 60) return;
            }

            // EASY mode (and AI-NORMAL): strictly 1 note per tick across ALL channels to guarantee no chords
            const key = (effectiveDifficulty === 'EASY' || (isAiGenerated && difficulty === 'NORMAL'))
                ? `GLOBAL_${n.quantizedStartTick}`
                : `${n.channel}_${n.quantizedStartTick}`;

            const count = seenCounts.get(key) || 0;
            if (count < maxLimit) {
                collapsed.push(n);
                seenCounts.set(key, count + 1);
                lastAcceptedTick = n.quantizedStartTick;
            }
        });

        // 3. Apply Time Correction (Sync Fix)
        RhythmQuantizer.applyTimeCorrection(collapsed, midi);

        const preparedNotes = collapsed.map(n => {
            let durationMs = n.duration * 1000;
            let isHold = durationMs >= holdThresholdMs;

            // [NEW] AI-NORMAL Transformer: Convert ~50% of holds to TAPs while keeping timing
            if (isAiGenerated && difficulty === 'NORMAL' && isHold) {
                const isOnQuarterBeat = n.quantizedStartTick % midi.ppq === 0;
                if (!isOnQuarterBeat) {
                    // Convert to TAP: Maintain timing but remove hold requirement
                    isHold = false;
                    durationMs = 80; // Standard tap duration
                }
            }

            return {
                ...n,
                durationMs: durationMs,
                isHold: isHold,
                endTick: n.ticks + (isHold ? n.durationTicks : Math.round((80 / 1000) * (midi.ppq * midi.bpm / 60))), 
                isHolding: false,
                accumulatedHoldTime: 0,
                type: isHold ? 'HOLD' : 'TAP',
                lane: -1,
                isProcessed: false
            } as VisualNote;
        });

        const patterns = PatternAnalyzer.analyze(preparedNotes as any[]);
        let finalResult = LaneAllocator.assignLanes(patterns, laneCount, effectiveDifficulty);
        
        // 4. [NEW] Trim Hand Conflicts
        // Ensure no long note overlaps with a subsequent note on the same hand.
        finalResult = this.trimHandConflicts(finalResult, laneCount);

        console.log(`[NoteFactory] Charted ${finalResult.length} notes (Holds: ${finalResult.filter(n => n.isHold).length}).`);
        if (finalResult.length > 0) {
            console.log(`[NoteFactory] First 5 notes sample:`, finalResult.slice(0, 5).map(n => ({
                tick: n.ticks, time: n.time, lane: n.lane, duration: n.duration, isHold: n.isHold
            })));
        }
        if (finalResult.length > 20000) {
            return finalResult.slice(0, 20000);
        }
        return finalResult;
    }

    /**
     * Post-processing pass: Trims long note durations if they conflict with 
     * a same-hand, different-lane note starting later.
     */
    private static trimHandConflicts(notes: VisualNote[], laneCount: number): VisualNote[] {
        // Ensure notes are sorted by time for linear scan
        const sorted = [...notes].sort((a, b) => a.time - b.time);
        
        const activeHoldInHand: { 'left': VisualNote | null, 'right': VisualNote | null } = {
            'left': null,
            'right': null
        };

        const getHand = (lane: number): 'left' | 'right' => {
            if (laneCount === 4) return lane < 2 ? 'left' : 'right';
            return lane < 3 ? 'left' : 'right';
        };

        const bufferMs = 30; // 30ms gap to ensure release before next hit

        for (const note of sorted) {
            const hand = getHand(note.lane);
            const activeHold = activeHoldInHand[hand];

            // 1. If there's an active hold in the SAME HAND area...
            if (activeHold && activeHold !== note) {
                const holdEndTime = activeHold.time + (activeHold.durationMs / 1000);
                
                // 2. And it overlaps with the current note's start...
                // (Only if it's in a DIFFERENT lane, as same-lane overlap is already handled by hardware/allocator)
                if (activeHold.lane !== note.lane && holdEndTime > note.time - (bufferMs / 1000)) {
                    // 3. Trim it!
                    const newDurationMs = Math.max(0, (note.time - activeHold.time) * 1000 - bufferMs);
                    activeHold.durationMs = newDurationMs;
                    activeHold.duration = newDurationMs / 1000;
                    
                    // If it was trimmed to basically zero, it's effectively a tap
                    if (newDurationMs < 100) {
                        activeHold.isHold = false;
                        activeHold.type = 'TAP';
                    }
                    
                    // Clear it as it's now "ended" before this note
                    activeHoldInHand[hand] = null;
                }
            }

            // If current note is a hold, track it as the active one for this hand
            if (note.isHold) {
                activeHoldInHand[hand] = note;
            }

            // Cleanup: If a hold ended naturally before this note, clear the tracker
            ['left', 'right'].forEach((h: any) => {
                const hold = activeHoldInHand[h as 'left' | 'right'];
                if (hold && hold.time + (hold.durationMs / 1000) <= note.time) {
                    activeHoldInHand[h as 'left' | 'right'] = null;
                }
            });
        }

        return sorted;
    }
}
