import type { ParsedMidi, GameNote } from '../../../../core/audio/MidiParser';
import { MelodyAnalyzer } from '../../../../core/audio/MelodyAnalyzer';
import { LegacyRhythmQuantizer, type LegacyQuantizedNote } from './LegacyRhythmQuantizer';
import { LegacyPatternAnalyzer } from './LegacyPatternAnalyzer';
import { LegacyLaneAllocator } from './LegacyLaneAllocator';
import { DifficultyManager } from '../DifficultyManager';

export interface LegacyVisualNote extends GameNote {
    lane: number;
    isProcessed: boolean;
    quantizedStartTick: number;
    quantizedEndTick: number;
    isOnBeat?: boolean;
    isStrongBeat?: boolean;
    durationMs: number;
    isHold: boolean;
    endTick: number;
    isHolding: boolean;
    accumulatedHoldTime: number;
    type: 'TAP' | 'HOLD';
}

export class LegacyNoteFactory {
    public static createLegacyNotes(
        midi: ParsedMidi,
        laneCount: number = 4,
        forcedChannels: number[] | null = null,
        difficulty: string = 'NORMAL',
        measureConfig: [number, number][] | null = null
    ): LegacyVisualNote[] {
        const ppq = midi.ppq;

        const measureMap = new Map<number, number>();
        if (measureConfig && Array.isArray(measureConfig)) {
            measureConfig.forEach(entry => {
                if (Array.isArray(entry) && entry.length >= 2) {
                    measureMap.set(Number(entry[0]), Number(entry[1]));
                }
            });
        }

        let autoGeneratedConfig: Map<number, number> | null = null;
        if (measureMap.size === 0) {
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
        }

        const diffManager = new DifficultyManager(difficulty, {
            isAiGenerated: false,
            bpm: midi.bpm,
            ppq: midi.ppq
        });

        const collectNotes = (map: Map<number, number>, autoMap: Map<number, number> | null) => {
            const notesToProcess: GameNote[] = [];
            midi.tracks.forEach((track: any) => {
                track.notes.forEach((note: any) => {
                    if (note.velocity < 13) return;
                    const measureIdx = Math.floor(note.ticks / (ppq * 4));
                    
                    const isDrum = (note.channel === 9 || track.isDrum || track.name?.toLowerCase().includes('drums'));
                    
                    if (forcedChannels && forcedChannels.length > 0) {
                        if (forcedChannels.includes(note.channel)) notesToProcess.push(note);
                        return;
                    }
                    
                    let targetChannel = null;
                    if (map.has(measureIdx)) targetChannel = map.get(measureIdx)!;
                    else if (autoMap && autoMap.has(measureIdx)) targetChannel = autoMap.get(measureIdx)!;
                    else {
                        for (let i = measureIdx; i >= 0; i--) {
                            if (map.has(i)) { targetChannel = map.get(i)!; break; }
                            if (autoMap && autoMap.has(i)) { targetChannel = autoMap.get(i)!; break; }
                        }
                    }

                    const isPrimary = (targetChannel !== null && note.channel === targetChannel);
                    
                    let shouldAccept = false;
                    if (isPrimary) {
                        shouldAccept = true;
                    } else if (isDrum && diffManager.shouldIncludeDrums()) {
                        shouldAccept = true;
                    }

                    if (shouldAccept) {
                        if (isPrimary) (note as any).isPrimary = true;
                        notesToProcess.push(note);
                    }
                });
            });
            return notesToProcess;
        };

        let initialNotes = collectNotes(measureMap, autoGeneratedConfig);
        if (initialNotes.length === 0 && !forcedChannels) {
            autoGeneratedConfig = MelodyAnalyzer.suggestGapFilling(midi);
            initialNotes = collectNotes(new Map(), autoGeneratedConfig);
        }

        let notesToProcess = initialNotes
            .filter(n => n.duration > 0.01)
            .sort((a, b) => a.ticks - b.ticks)
            .slice(0, 20000);

        if (notesToProcess.length === 0) return [];

        const quantized = LegacyRhythmQuantizer.quantize(notesToProcess, midi.ppq);

        const collapsed: LegacyQuantizedNote[] = [];
        const seenCounts = new Map<string, number>();
        const maxLimit = diffManager.getNoteChordLimit();
        const holdThresholdMs = diffManager.getAiHoldThresholdMs(); // Uniform threshold

        // Sort by primary status to ensure vocal priority during monophonic collapse
        quantized.sort((a, b) => {
            if (a.quantizedStartTick !== b.quantizedStartTick) return a.quantizedStartTick - b.quantizedStartTick;
            return ((b as any).isPrimary ? 1 : 0) - ((a as any).isPrimary ? 1 : 0);
        });

        quantized.forEach(n => {
            const key = diffManager.isGlobalChordSuppressionActive()
                ? `GLOBAL_${n.quantizedStartTick}`
                : `${n.channel}_${n.quantizedStartTick}`;

            const count = seenCounts.get(key) || 0;
            if (count < maxLimit) {
                collapsed.push(n);
                seenCounts.set(key, count + 1);
            }
        });

        LegacyRhythmQuantizer.applyTimeCorrection(collapsed, midi);

        const preparedNotes = collapsed.map(n => {
            let durationMs = n.duration * 1000;
            let isHold = durationMs >= holdThresholdMs;

            return {
                ...n,
                durationMs: durationMs,
                isHold: isHold,
                endTick: n.ticks + (isHold ? n.durationTicks : Math.round((80 / 1000) * (midi.ppq * midi.bpm / 60))), 
                isHolding: false,
                accumulatedHoldTime: 0,
                type: isHold ? 'HOLD' : 'TAP',
                lane: -1,
                isProcessed: false
            } as LegacyVisualNote;
        });

        const segments = LegacyPatternAnalyzer.analyze(preparedNotes);
        let finalResult = LegacyLaneAllocator.assignLanes(segments, laneCount, difficulty);
        
        return this.trimHandConflicts(finalResult, laneCount);
    }

    private static trimHandConflicts(notes: LegacyVisualNote[], laneCount: number): LegacyVisualNote[] {
        const sorted = [...notes].sort((a, b) => a.time - b.time);
        const activeHoldInHand: { 'left': LegacyVisualNote | null, 'right': LegacyVisualNote | null } = {
            'left': null, 'right': null
        };

        const getHand = (lane: number): 'left' | 'right' => {
            if (laneCount === 4) return lane < 2 ? 'left' : 'right';
            return lane < 3 ? 'left' : 'right';
        };

        const bufferMs = 30;

        for (const note of sorted) {
            const hand = getHand(note.lane);
            const activeHold = activeHoldInHand[hand];

            if (activeHold && activeHold !== note) {
                const holdEndTime = activeHold.time + (activeHold.durationMs / 1000);
                if (activeHold.lane !== note.lane && holdEndTime > note.time - (bufferMs / 1000)) {
                    const newDurationMs = Math.max(0, (note.time - activeHold.time) * 1000 - bufferMs);
                    activeHold.durationMs = newDurationMs;
                    activeHold.duration = newDurationMs / 1000;
                    if (newDurationMs < 100) {
                        activeHold.isHold = false;
                        activeHold.type = 'TAP';
                    }
                    activeHoldInHand[hand] = null;
                }
            }

            if (note.isHold) activeHoldInHand[hand] = note;

            ['left', 'right'].forEach((h: any) => {
                const hold = activeHoldInHand[h as 'left' | 'right'];
                if (hold && hold.time + (hold.durationMs / 1000) <= note.time) {
                    activeHoldInHand[h as 'left' | 'right'] = null;
                }
            });
        }

        return sorted;
    }
}
